steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/ethereal-fort-435120-d1/joeljose-100904791/app:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/ethereal-fort-435120-d1/joeljose-100904791/app:$COMMIT_SHA']
 
images:
  - 'us-central1-docker.pkg.dev/ethereal-fort-435120-d1/joeljose-100904791/app:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
