steps:
  # Step 1: Use Docker Cloud Builder to build the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/[PROJECT_ID]/joeljose-100904791/$_COMMIT_SHA', '.']

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/[PROJECT_ID]/joeljose-100904791/$_COMMIT_SHA']

options:
  logging: REGIONAL_USER_OWNED_BUCKET
