steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/ethereal-fort-435120/joeljose-100904791/app:$_COMMIT_SHA', '.']

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/ethereal-fort-435120/joeljose-100904791/app:$_COMMIT_SHA']

options:
  logging: CLOUD_LOGGING_ONLY
